package net.tarilabs.reex2014;

import com.sun.syndication.feed.synd.SyndContent;
import com.sun.syndication.feed.synd.SyndEntry;
import com.sun.syndication.feed.synd.SyndFeed;

import org.kie.api.runtime.rule.RuleContext;

import org.slf4j.Logger;

global Logger LOG;

import twitter4j.Status;

declare SyndFeed
	@role(event)
	@expires(24h)
end

declare Status
	@role(event)
	@expires(24h)
end

declare Alert
	@role(event)
	@timestamp(ts)
	@expires(7d)
end

declare window lastAlert
    Alert() over window:length( 1 ) // from entry-point DEFAULT
end

query "Alert"
	$alert : Alert()
end

function long sessionCurrentTime(RuleContext kcontext) {
	return kcontext.getKieRuntime().getSessionClock().getCurrentTime();
}

/**
 * Syntactic sugar - without using custom Evaluators. Instead of using regexp for req 'find a keyword in text, case-unsensitive', I will leverage the MVEL 'contains' operator: but this will require convention on lowercase, I guess.
 * This will not degrade performance badly, however rules shall be much more legible ...and easy for screenshots =)
*/
function String l(String text) {
	return text.toLowerCase();
}

rule "Ciao"
no-loop
when
then
	LOG.info("Ciao");
end