package net.tarilabs.reex2014;

import com.sun.syndication.feed.synd.SyndEntry;
import com.sun.syndication.feed.synd.SyndFeed;

/* If the RSS entry text contains the word 'sciopero' or 'strike' (case-unsensitive),
   then raise a strike warning alert
*/
rule "RSS Strike warning alert"
no-loop
when
	$feed : SyndFeed()
	$entry : SyndEntry( l(description.value) contains "sciopero"
					    || l(description.value) contains "strike"
					   ) from $feed.entries
then
	Alert<SyndEntry> alert = new Alert<SyndEntry>(sessionCurrentTime(kcontext),
													"Strike warning alert",	
													AlertType.WARNING,
													$entry);
	insert(alert);
	LOG.info("ALERT raised: " + alert);
end	




















/* LHS a way to re-cycle on this typed-Alert, for future reference
	Alert($ref : ref#SyndFeed.entries)
	$entry : SyndEntry(description.value matches "(?i).*sciopero.*" 
					   || description.value matches "(?i).*strike.*" ) from $ref
*/